baseurl = "http://localhost:1313/"
Title = "work in progress."
# Copyright notice. This is displayer in the footer.
copyright = "tea bought it to life"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "@andressamcosta"
  github = "andressacosta"
  linkedin = "andressa-costa-77748321"
  # Google Analytics API key.
  ga_api_key = "Your Google Analytics tracking id"
  # Logo image. This is displayed ogp image.
  #logo = "/path/to/logo"
  #favicon = "/path/to/favicon"

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "non-code"
    name = "Non code"
    url = "/non-code/"
    weight = 3

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2018"

